config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all

  # You can have the root of your site routed with "root"
  root 'landing#index'

  # devise routes
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  # root level routes
  get '/', to: 'landing#index', as: 'landing_index'
  get '/pricing', to: 'landing#pricing', as: 'landing_pricing'
  get '/about', to: 'landing#about', as: 'landing_about'
  match '/contact_us', to: 'landing#contact_us', via: [:get, :post], as: 'landing_contact_us'
  get '/sign_up', to: 'landing#sign_up', as: 'landing_sign_up'
  get '/create_profile', to: 'landing#create_profile', as: 'landing_create_profile'
  get '/search', to: 'landing#search', as: 'landing_search'

  mount Ckeditor::Engine => '/ckeditor'
  
  resources :establishments, shallow: true do
    member do
      delete :destroy_photo
    end
    
    resources :staff do
      member do
        get 'image'
        get 'image_done'
      end
    end
  end

  resources :users
  resources :user_profiles do
    member do
      post :add_photo
      post :create_profile_image
      post :create_banner_image
      delete :destroy_photo
    end
  end

  scope '/images' do
    get 'presigned', to: 'images#presigned'
  end

  # api
  namespace :api do
    namespace :v1 do
      resources :search, only: [:index]
      resources :search_location, only: [:index]
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
  validates :name, presence: true
  has_one :location, dependent: :destroy
  has_one :social_link, as: :social_linkable, dependent: :destroy
  has_many :staff, dependent: :destroy
  has_many :service_times, dependent: :destroy

  has_one :profile_image, -> {where imageable_type: 'EstablishmentProfileImage'},
    class_name: :Image, foreign_key: :imageable_id, 
    foreign_type: :imageable_type, dependent: :destroy
  has_one :banner_image, -> {where imageable_type: 'EstablishmentBannerImage'},
    class_name: :Image, foreign_key: :imageable_id, 
    foreign_type: :imageable_type, dependent: :destroy

  has_many :photos, -> {where imageable_type: 'EstablishmentPhoto'},
    class_name: :Image, foreign_key: :imageable_id,
    foreign_type: :imageable_type, dependent: :destroy

  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :staff
  accepts_nested_attributes_for :service_times, allow_destroy: true, :reject_if => proc {|attrs| attrs['day'].blank? or attrs['start_time'].blank?}
  accepts_nested_attributes_for :social_link

  accepts_nested_attributes_for :banner_image
  accepts_nested_attributes_for :profile_image
  accepts_nested_attributes_for :photos
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :set_establishment, only: [:show, :edit, :destroy, :update]
  before_action :set_google_api_key, only: [:new, :edit]
  
  # GET /establishments
  # GET /establishments.json
  def index
    @establishments = Establishment.all
  end

  # GET /establishments/1
  # GET /establishments/1.json
  def show
    respond_to do |format|
      format.html do
        gon.stores = ["AppEstablishmentStore"] 
        gon.jbuilder  
      end

      format.json { render :show }
    end    
  end

  # GET /establishments/new
  def new
    @establishment = Establishment.new
    @establishment.build_location
    @establishment.service_times.build()

    unless params['place_id']
      flash[:alert] = "You must register a church from the church search screen"
    else
      pid = params['place_id']
      @establishment.place_id = pid
      @establishment.location.place_id = pid
    end
  end

  # GET /establishments/1/edit
  def edit
    @establishment.service_times.build()
  end

  # POST /establishments
  # POST /establishments.json
  def create
    @establishment = Establishment.new(establishment_params)

    respond_to do |format|
      if @establishment.save
        if @establishment.profile_image
          @establishment.profile_image.save
        end

        if @establishment.banner_image
          @establishment.banner_image.save
        end

        format.html { redirect_to @establishment, notice: 'Establishment was successfully created.' }
        format.json { render :show, status: :created, location: @establishment }
      else
        format.html { render :new }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establishments/1
  # PATCH/PUT /establishments/1.json
  def update
    pia = params['establishment']['profile_image_attributes']
    bia = params['establishment']['banner_image_attributes']

    respond_to do |format|
      # Are we updating pictures or establishment itself?
      if pia || bia
        # Updating one of the pictures
        if pia and pia['url']
          # Process profile image that have already been uploaded to S3
          # but awaits format processing
          @establishment.profile_image.enqueue_image pia['url']
          format.json { render :show }
        end

        if bia and bia['url']
          @establishment.banner_image.enqueue_image bia['url']
          format.json { render :show }
        end

      # There is new photo url to add
      elsif params['establishment']['new_photo_url']
        @establishment.photos.build.enqueue_image params['establishment']['new_photo_url']
        format.json { render :show }
      # Okay we are updating establishment
      else
        if @establishment.update(establishment_params)
          format.html { redirect_to @establishment, notice: 'Establishment was successfully updated.' }
          format.json { render :show, status: :ok, location: @establishment }
        else
          format.html { render :edit }
          format.json { render json: @establishment.errors, status: :unprocessable_entity }
        end
      end
      
      # if bia and (bia['graphic'].blank? and bia['graphic_cache'].blank?)
      #   params['establishment'].delete 'banner_image_attributes'
      # end

      
    end
  end


  # DELETE /establishments/1
  # DELETE /establishments/1.json
  def destroy
    @establishment.destroy
    respond_to do |format|
      format.html { redirect_to establishments_url, notice: 'Establishment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Destroys photo if it belongs to the establishment,
  # graphic removal is done on background.
  def destroy_photo
    @establishment = Establishment.find(params[:id])

    # If photo to destory belongs to this establishment
    if @establishment.photos.any? { |p| p.id == params[:photo_id] }
      # Nullify image so we can send correct version of establishment
      # back to frontend
      image = Image.find(params[:photo_id])
      image.imageable_type = nil
      image.imageable_id = nil
      image.save

      @establishment.reload

      # Now remove image
      image.enqueue_removal
      respond_to do |format|
        format.json { render :show }
      end
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_establishment
    @establishment = Establishment.find(params[:id])
    unless @establishment.location
      @establishment.build_location
    end

    unless @establishment.social_link
      @establishment.build_social_link
    end

    @social_link = @establishment.social_link

    unless @establishment.profile_image
      @establishment.build_profile_image
      @establishment.profile_image.processed = true
    end

    unless @establishment.banner_image
      @establishment.build_banner_image
      @establishment.banner_image.processed = true
    end

    # set_service_times()
  end

  def set_service_times
    # build our service times, 5 by default
    unless @establishment.service_times.count > 0
      @establishment.service_times.build()
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def establishment_params
    params.require(:establishment)
    .permit(:name, :description, :website, :key, :phone, :denomination,
            :admin_phone, :email, :admin_email, :leader, :pastor,
            location_attributes: [:id, :latitude, :longitude, :address, :city, :state, :zip, :place_id],
            social_link_attributes: [:id, :facebook, :twitter, :instagram, :yelp, :google_plus, :youtube],
            profile_image_attributes: [:id, :graphic, :graphic_cache],
            banner_image_attributes: [:id, :graphic, :graphic_cache],
            service_times_attributes: [:id, :start_time, :day, :service_name, :_destroy],
           )
  end

  def set_google_api_key
    @google_api_key = ENV['GOOGLE_JS_AUTOCOMPLETE']
  end
end

app/views/establishments/_form.html.haml
= form_for(@establishment) do |f|
  - if @establishment.errors.any?
    #error_explanation
      %h2
        = pluralize(@establishment.errors.count, "error")
        prohibited this establishment from being saved:
      %ul
        - @establishment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :leader
    = f.text_field :leader
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :admin_phone
    = f.text_field :admin_phone
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :admin_email
    = f.text_field :admin_email
  .field
    = f.fields_for :profile_image do |profile_image_form|
      = profile_image_form.label :graphic, "Choose your profile image"
      = profile_image_form.file_field :graphic
      = profile_image_form.hidden_field :graphic_cache
  .field
    = f.fields_for :banner_image do |banner_image_form|
      = banner_image_form.label :graphic, "Choose your banner image"
      = banner_image_form.file_field :graphic
      = banner_image_form.hidden_field :graphic_cache
  .field
    = f.label :description
    = f.cktext_area :description, class: 'ckeditor'
  = f.fields_for :location do |builder|
    = render 'location_fields', :f => builder
  = f.simple_fields_for :social_link do |slf|
    = render 'social/social_fields', f: slf

  .field
    %h4{style: "margin-bottom: 0.625rem"} Church service times
    .duplicatable_nested_form_container
      = f.simple_fields_for :service_times do |st_form|
        .duplicatable_nested_form
          %fieldset
            = st_form.input :service_name
            = st_form.select :day, ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
            = st_form.input :start_time, input_html: {type: 'time'}
            - unless st_form.object.new_record?
              = st_form.input :_destroy, as: :hidden
            .text-right
              = link_to 'Remove', '#', class: 'destroy_nested_form'
      = link_to 'Add service time', '#', class: 'duplicate_nested_form'
    
  .actions
    = f.submit

app/views/establishments/_location_fields.html.haml
.field
  = f.label :address
  = f.text_field :address
= f.hidden_field :latitude
= f.hidden_field :longitude
/ One per page intended
:javascript
  initMap = function() {
    var input = document.getElementById('establishment_location_attributes_address');
    var autocomplete = new google.maps.places.Autocomplete(input);

    autocomplete.addListener('place_changed', function() {
      var place = autocomplete.getPlace();
      document.getElementById('establishment_location_attributes_latitude').value = place.geometry.location.lat();
      document.getElementById('establishment_location_attributes_longitude').value = place.geometry.location.lng();
      document.getElementById('establishment_location_attributes_address').value = place.formatted_address;
    });
  }

app/views/establishments/index.html.haml
%p#notice= notice
%h1 Listing Establishments
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @establishments.each do |establishment|
      %tr
        %td= establishment.name
        %td= establishment.description.html_safe unless establishment.description.nil?
        %td
          = link_to 'Show', establishment
          |
        %td
          = link_to 'Edit', edit_establishment_path(establishment)
          |
        %td= link_to 'Destroy', establishment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Establishment', new_establishment_path

app/views/establishments/new.html.haml
.landing-contact.establishment-register
  .hero-container
    %h2.text-center
      The best investment your Church will ever make!
  .container.container-overlay
    - if flash[:notice]
      .success.callout.text-center
        %p
          = flash[:notice]
    - else
      .row
        .small-12
          %h3.text-center{style: 'margin-bottom: 0'} Register Your Church Today!
          %p.text-center{style: 'margin-top: 0'} Please fill out the form below.

          = form_for @establishment,
              html: {"data-abide" => " ", novalidate: " "} do |f|
            - if @establishment.errors.any?
              #error_explanation
                %h2
                  = pluralize(@establishment.errors.count, "error")
                  prohibited this form from being submitted:
                %ul
                  - @establishment.errors.full_messages.each do |message|
                    %li= message
            .row{style: "margin-top:4rem"}
              .small-12.medium-6.column.text-center.medium-text-left
                = f.text_field :name, placeholder: 'Name*', required: true
                %span.form-error
                  Church name is required
              .small-12.medium-6.column.text-center.medium-text-left
                = f.text_field :denomination, placeholder: 'Denomination*', required: true
                %span.form-error
                  Denomination is required
            .row
              .small-12.medium-6.column.text-center.medium-text-left
                = f.text_field :leader, placeholder: 'Pastor full name*', required: true
                %span.form-error
                  Pastor is required
              .small-12.medium-6.column.text-center.medium-text-left
                = f.fields_for :location do |l|
                  = l.text_field :address, required: true, placeholder: 'Address*'
            .row
              .small-12.medium-6.column.text-center.medium-text-left
                = f.phone_field :phone, placeholder: 'Phone number*', required: true
                %span.form-error
                  Phone number is required
              .small-12.medium-6.column.text-center.medium-text-left
                = f.fields_for :location do |l|
                  .row
                    .small-6.columns
                      = l.text_field :city, required: true, placeholder: 'City*', disabled: true
                      %span.form-error
                        City is required
                    .small-3.columns
                      = l.text_field :state, required: true, placeholder: 'State*', disabled: true
                      %span.form-error
                        State is required
                    .small-3.columns
                      = l.text_field :zip, required: true, placeholder: 'Zip*', disabled: true
                      %span.form-error
                        Zip is required
                      = l.hidden_field :place_id
                      = l.hidden_field :latitude
                      = l.hidden_field :longitude
            .row
              .small-12.medium-6.column.text-center.medium-text-left
                = f.email_field :email, placeholder: 'Email*', required: true
                %span.form-error
                  Email is required
              .small-12.medium-6.column.text-center.medium-text-left
                = f.phone_field :website, placeholder: 'Website'

            .row
              .small-12.column.text-center.medium-text-right
                = f.button 'Submit', type: :submit, value: 'submit'

app/views/establishments/show.html.haml
.profile-page.establishment-show
  .row.align-center
    .columns.small-12.medium-9
      .row.columns.cover-container
        .banner-image-container
          = react_component "EstablishmentBannerImageContainer"
        .profile-image-container
          = react_component "EstablishmentProfileImageContainer"
        .profile-title
          = @establishment.name
        .cover-header
          .row.align-right
            .columns.small-6.no-pad-right.z-index-10
              .profile-phone
                %i.ci.ci-phone
                %span.phone-text
                  = react_component "EstablishmentPhoneContainer"
            .columns.small-4.medium-2.no-pad-sides.z-index-9
              .hollow.secondary.expanded.button.cover-button
                %i.ci.ci-home.ci-12
                Join 
            .columns.small-4.medium-2.no-pad-sides.z-index-8
              .hollow.secondary.expanded.button.cover-button
                %i.ci.ci-bookmark.ci-12
                Bookmark
            .columns.small-4.medium-2.no-pad-left
              .icon-block
                %i.ci.ci-sharing.ci-32
                %i.ci.ci-messaging.ci-32
                %i.ci.ci-giving.ci-32
      .row
        .columns.small-12.medium-6
          .map-container
            .map-header
              = react_component "EstablishmentLocationContainer"
            = react_component "EstablishmentMapContainer"
          .service-container
            = react_component "EstablishmentServicesContainer"
            
          .widget-container
            = react_component "EstablishmentPhotosContainer"
          .widget-container
            %img{ src: "http://placehold.it/420x350/DDD?text=Giving", width: "100%" }
        .columns.small-12.medium-6
          = react_component "EstablishmentDescriptionContainer"
          .widget-container
            %img{ src: "http://placehold.it/420x200/DDD?text=Members", width: "100%" }
          .widget-container
            %img{ src: "http://placehold.it/420x400/DDD?text=Livestreamers", width: "100%" }
          .widget-container
            %img{ src: "http://placehold.it/420x200/DDD?text=Calendars", width: "100%" }

    .columns.medium-3
      .row.hide-for-small-only.side-ads
        .columns.small-12
          %img{ src: "http://placehold.it/260x180/DDD?text=Ad+goes+here!", width: "100%", height: "100%" }
        .columns.small-12
          %img{ src: "http://placehold.it/260x180/DDD?text=Ad+goes+here!", width: "100%", height: "100%" }
        .columns.small-12
          %img{ src: "http://placehold.it/260x180/DDD?text=Ad+goes+here!", width: "100%", height: "100%" }

      .widget-container
        %img{ src: "http://placehold.it/420x150/DDD?text=Blogs", width: "100%" }

%div
  = render "social/social_link_list"

= link_to 'Staff', establishment_staff_index_path(@establishment)
|
= link_to 'Edit', edit_establishment_path(@establishment)
|
= link_to 'Back', establishments_path