config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all

  # You can have the root of your site routed with "root"
  root 'landing#index'

  # devise routes
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  # root level routes
  get '/', to: 'landing#index', as: 'landing_index'
  get '/pricing', to: 'landing#pricing', as: 'landing_pricing'
  get '/about', to: 'landing#about', as: 'landing_about'
  match '/contact_us', to: 'landing#contact_us', via: [:get, :post], as: 'landing_contact_us'
  get '/sign_up', to: 'landing#sign_up', as: 'landing_sign_up'
  get '/create_profile', to: 'landing#create_profile', as: 'landing_create_profile'
  get '/search', to: 'landing#search', as: 'landing_search'

  mount Ckeditor::Engine => '/ckeditor'
  
  resources :establishments, shallow: true do
    member do
      delete :destroy_photo
    end
    
    resources :staff do
      member do
        get 'image'
        get 'image_done'
      end
    end
  end

  resources :users
  resources :user_profiles do
    member do
      post :add_photo
      post :create_profile_image
      post :create_banner_image
      delete :destroy_photo
    end
  end

  scope '/images' do
    get 'presigned', to: 'images#presigned'
  end

  # api
  namespace :api do
    namespace :v1 do
      resources :search, only: [:index]
      resources :search_location, only: [:index]
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "The Fellowship App"

    = render 'favicon'

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  -# Google places search
  -# calling initMarkerWithLabel which adds support of custom Markers. Defined in
  -# vendor/assets/javasripts/markerwithlabel.js
  %script{:src => "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_JS_AUTOCOMPLETE']}&libraries=places,geometry&callback=initMarkerWithLabel"}

  -# Initialize foundation after main content loaded
  :javascript
    $(document).on('turbolinks:load', function() { $(document).foundation(); });

  -# GA only in production
  - if Rails.env.production?
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-44009225-5', 'auto');
      ga('send', 'pageview');


  %body
    = Gon::Base.render_data

    -# Alerts and notice flashes
    - if notice
      .success.callout{"data-closable" => ""}
        = notice
        %button.close-button{"aria-label" => "Dismiss alert", "data-close" => "", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
    - if alert
      .alert.callout{"data-closable" => ""}
        = alert
        %button.close-button{"aria-label" => "Dismiss alert", "data-close" => "", :type => "button"}
          %span{"aria-hidden" => "true"} &times;

    .body
      -# Render the header
      .title-wrapper
        .row.title-row
          .title-bar.small-12.hide-for-large{"data-responsive-toggle" => "dropdown-menu",
                                             "data-hide-for" => "large"}
            .title-bar-left
              %a.title-brand{:href => landing_index_path}= image_tag "logo-short.png"
            .title-bar-right
              %button.menu-icon{type: "button", "data-toggle" => ""}
              %ul#dropdown-menu
                = render 'landing_links'
          #desktop-menu.top-bar.show-for-large.small-12
            .top-bar-left
              %a.title-brand{:href => landing_index_path}= image_tag "logo-short.png"
              = form_tag(landing_search_path, method: :get, class: 'header-search-form') do
                = react_component('ChurchSearchContainer', {})
                = react_component('LocationSearchContainer', {})
            .top-bar-right
              %ul.menu
                = render 'landing_links'

      -# Render the main content
      = yield

      -# Render the footer
      .container.bg-blue.footer
        .row
          .small-12.large-6.text-center.large-text-left
            %ul.menu.footer-links{:style => 'margin-top:25px'}
              = render 'landing_links'
          .small-12.large-6
            = render 'landing/social_links'
        .row{:style => 'padding-top:30px'}
          .small-12.large-6
            %small.copyright 
              Copyright ©
              2015 -
              = Date.today.year
              The Fellowship App. All Rights Reserved.
          .small-12.large-6
            %small.copyright We value your privacy. None of the details supplied will be shared with external parties